apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-hw1-d04ba
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/spring-boot-hw1-d04ba.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-boot-hw1-d04ba
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
