apiVersion: v1
kind: Service
metadata:
  name: spring-boot-hw1-d04ba-service
spec:
  type: NodePort
  selector:
    app: spring-boot-hw1-d04ba
  ports:
    - protocol: TCP
      port: 8231
      targetPort: 8080
